### ISSUE TITLE
Get first unused nonce?

### ISSUE THREAD

**Issue by boris-savic** [bokkypoobah/BokkyPooBahsTokenTeleportationServiceSmartContract#3]
Great work!

It seems to me that the current implementation does not allow querying for the last used or first unused (depends on the preference) nonce. So the client applications would need to keep track of all the nonces, and this could prove to be an issue in case the client application looses the nonce history as it would have to retry all the nonces until it finds the first unused one. 

Perhaps something like this would allow the client app to query for the first unused nonce:

```
mapping(address => uint) nonces;

function getNonce(address spender) public view returns (uint) {
   return nonces[spender] + 1;
}

```

**Comment by bokkypoobah** [comment]
Thanks for your suggestion on using the nonce. I've now implemented it and it will make the provision of the BTTS service easier.
